# database configs
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://${MYSQL_DB_URL}/tb_transaction_bank
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Specify the OpenAPI documentation
springdoc:
  swagger-ui:
    enabled: true
    path: swagger-ui.html
  api-docs:
    path: /api-docs
